import type { Metadata } from 'next'
import { Comforter } from 'next/font/google'
const inter = Comforter({
  subsets: ['latin'],
  weight: '400'
})
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='w-screen h-screen relative'>
        <div className={inter.className}>
          <div className=' absolute flex'>{children}</div>
        </div>
      </body>
    </html>
  )
}
