import type { Metadata } from 'next'

import Header from '../components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className='w-screen'>
        <Header />
      </div>
      <div className='mt-32 absolute flex'>{children}</div>
    </>
  )
}
